# Dependencies
markdown:            kramdown

redcarpet:
  extensions: ["tables", "fenced_code_block"]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

exclude:      ["*.Rmd"]


# Setup
title:               Data Mining course
tagline:             'Eksploracja danych, kurs dla studentów UKSW'
description:         'Eksploracja danych dla studentów WMP.SNŚ UKSW'
url:                 http://sebkaz.github.io/DataMining/
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Sebastian Zając
  url:               https://sebastianzajac.pl
  email:             s.zajac@uksw.eud.pl

# Custom vars
version:             1.0.0
